DELETE FROM plugin WHERE id = '19004';
DELETE FROM plugin_sid where plugin_id = '19004';
DELETE FROM software_cpe where plugin = 'websense_wsg:19004';
INSERT IGNORE INTO software_cpe (cpe, name, version, line, vendor, plugin) VALUES ('cpe:/o:Websense:Web Security Gateway:7.x','Web Security Gateway','7.x','','Websense', 'websense_wsg:19004');
INSERT IGNORE INTO plugin (id, type, name, description, product_type, vendor) VALUES (19004, 1, 'websense_wsg', 'websense_wsg', '1', 'Websense');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1, NULL, NULL, 'Websense Allowed: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 2, NULL, NULL, 'Websense Allowed: Business and Economy', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 3, NULL, NULL, 'Websense Allowed: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 4, NULL, NULL, 'Websense Allowed: Government', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 5, NULL, NULL, 'Websense Allowed: News and Media', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 6, NULL, NULL, 'Websense Allowed: Religion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 7, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 8, NULL, NULL, 'Websense Allowed: Special Events', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 9, NULL, NULL, 'Websense Allowed: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10, NULL, NULL, 'Websense Allowed: Abortion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11, NULL, NULL, 'Websense Allowed: Advocacy Groups', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 12, NULL, NULL, 'Websense Allowed: Entertainment', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 13, NULL, NULL, 'Websense Allowed: Gambling', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 14, NULL, NULL, 'Websense Allowed: Games', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 15, NULL, NULL, 'Websense Allowed: Illegal or Questionable', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 16, NULL, NULL, 'Websense Allowed: Job Search', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 17, NULL, NULL, 'Websense Allowed: Shopping', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 18, NULL, NULL, 'Websense Allowed: Sports', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 19, NULL, NULL, 'Websense Allowed: Tasteless', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 20, NULL, NULL, 'Websense Allowed: Travel', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 21, NULL, NULL, 'Websense Allowed: Vehicles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 22, NULL, NULL, 'Websense Allowed: Violence', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 23, NULL, NULL, 'Websense Allowed: Weapons', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 24, NULL, NULL, 'Websense Allowed: Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 25, NULL, NULL, 'Websense Allowed: Militancy and Extremist', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 26, NULL, NULL, 'Websense Allowed: Racism and Hate', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 27, NULL, NULL, 'Websense Allowed: Health', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 28, NULL, NULL, 'Websense Allowed: Information technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 29, NULL, NULL, 'Websense Allowed: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 64, NULL, NULL, 'Websense Allowed: User-Defined', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 65, NULL, NULL, 'Websense Allowed: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 66, NULL, NULL, 'Websense Allowed: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 67, NULL, NULL, 'Websense Allowed: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 68, NULL, NULL, 'Websense Allowed: Business and Economy', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 69, NULL, NULL, 'Websense Allowed: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 70, NULL, NULL, 'Websense Allowed: Entertainment', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 72, NULL, NULL, 'Websense Allowed: Government', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 73, NULL, NULL, 'Websense Allowed: Government', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 74, NULL, NULL, 'Websense Allowed: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 75, NULL, NULL, 'Websense Allowed: Information Technology - Proxy Avoidance', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 76, NULL, NULL, 'Websense Allowed: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 78, NULL, NULL, 'Websense Allowed: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 79, NULL, NULL, 'Websense Allowed: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 80, NULL, NULL, 'Websense Allowed: Information Technology - Hacking', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 81, NULL, NULL, 'Websense Allowed: News and Media', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 82, NULL, NULL, 'Websense Allowed: Religion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 83, NULL, NULL, 'Websense Allowed: Religion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 84, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 85, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 86, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 87, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 88, NULL, NULL, 'Websense Allowed: Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 89, NULL, NULL, 'Websense Allowed: Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 90, NULL, NULL, 'Websense Allowed: Drugs - Abused Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 91, NULL, NULL, 'Websense Allowed: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 92, NULL, NULL, 'Websense Allowed: Abortion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 93, NULL, NULL, 'Websense Allowed: Abortion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 94, NULL, NULL, 'Websense Allowed: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 95, NULL, NULL, 'Websense Allowed: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 96, NULL, NULL, 'Websense Allowed: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 97, NULL, NULL, 'Websense Allowed: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 98, NULL, NULL, 'Websense Allowed: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 99, NULL, NULL, 'Websense Allowed: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 100, NULL, NULL, 'Websense Allowed: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 101, NULL, NULL, 'Websense Allowed: Shopping', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 102, NULL, NULL, 'Websense Allowed: Shopping', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 103, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 107, NULL, NULL, 'Websense Allowed: Sport', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 108, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 109, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 110, NULL, NULL, 'Websense Allowed: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 111, NULL, NULL, 'Websense Allowed: Drugs - Marijuana', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 112, NULL, NULL, 'Websense Allowed: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 113, NULL, NULL, 'Websense Allowed: Bandwidth - Personal Network Storage and Backup', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 114, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 115, NULL, NULL, 'Websense Allowed: Bandwidth - Peer-to-Peer File Sharing', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 116, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 117, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 118, NULL, NULL, 'Websense Allowed: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 121, NULL, NULL, 'Websense Allowed: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 122, NULL, NULL, 'Websense Allowed: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 123, NULL, NULL, 'Websense Allowed: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 124, NULL, NULL, 'Websense Allowed: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 125, NULL, NULL, 'Websense Allowed: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 126, NULL, NULL, 'Websense Allowed: Security', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 128, NULL, NULL, 'Websense Allowed: Security - Malicious Web Sites', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 138, NULL, NULL, 'Websense Allowed: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 146, NULL, NULL, 'Websense Allowed: Miscellaneous', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 147, NULL, NULL, 'Websense Allowed: Miscellaneous - Images (Media)', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 148, NULL, NULL, 'Websense Allowed: Miscellaneous - Image Servers', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 149, NULL, NULL, 'Websense Allowed: Miscellaneous - Private IP Addresses', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 150, NULL, NULL, 'Websense Allowed: Miscellaneous - Content Delivery Networks', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 151, NULL, NULL, 'Websense Allowed: Miscellaneous - Dynamic Content', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 152, NULL, NULL, 'Websense Allowed: Miscellaneous - Network Errors', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 153, NULL, NULL, 'Websense Allowed: Miscellaneous - Uncategorized', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 154, NULL, NULL, 'Websense Allowed: Security - Spyware', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 156, NULL, NULL, 'Websense Allowed: Miscellaneous', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 164, NULL, NULL, 'Websense Allowed: Security - Phishing and Other Frauds', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 166, NULL, NULL, 'Websense Allowed: Security - Keyloggers', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 167, NULL, NULL, 'Websense Allowed: Security - Potentially Unwanted Software', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 172, NULL, NULL, 'Websense Allowed: Security - Bot Networks', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 191, NULL, NULL, 'Websense Allowed: Extended Protection', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 192, NULL, NULL, 'Websense Allowed: Extended Protection - Elevated Exposure', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 193, NULL, NULL, 'Websense Allowed: Extended Protection - Emerging Exploits', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 194, NULL, NULL, 'Websense Allowed: Extended Protection - Potentially Damaging Content', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 195, NULL, NULL, 'Websense Allowed: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 196, NULL, NULL, 'Websense Allowed: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 200, NULL, NULL, 'Websense Allowed: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 201, NULL, NULL, 'Websense Allowed: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 202, NULL, NULL, 'Websense Allowed: Parked Domain', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 203, NULL, NULL, 'Websense Allowed: Business and Economy', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 204, NULL, NULL, 'Websense Allowed: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 205, NULL, NULL, 'Websense Allowed: Security - Malicious Embedded Link', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 206, NULL, NULL, 'Websense Allowed: Security - Malicious Embedded iFrame', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 207, NULL, NULL, 'Websense Allowed: Security - Suspicious Embedded Link', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 208, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 209, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 210, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 211, NULL, NULL, 'Websense Allowed: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 212, NULL, NULL, 'Websense Allowed: Extended Protection', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 213, NULL, NULL, 'Websense Allowed: Security - Potentially Exploited Documents', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 214, NULL, NULL, 'Websense Allowed: Security - Mobile Malware', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 215, NULL, NULL, 'Websense Allowed: Information Technology - Unauthorized Mobile Marketplaces', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 216, NULL, NULL, 'Websense Allowed: Security - Custom-Encrypted Uploads', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 217, NULL, NULL, 'Websense Allowed: Security - Files Containing Passwords', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 218, NULL, NULL, 'Websense Allowed: Security - Advanced Malware Command and Control', 5, 5);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 219, NULL, NULL, 'Websense Allowed: Security - Advanced Malware Payloads', 5, 5);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1500, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1501, NULL, NULL, 'Websense Allowed: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1502, NULL, NULL, 'Websense Allowed: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1503, NULL, NULL, 'Websense Allowed: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1504, NULL, NULL, 'Websense Allowed: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1505, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1506, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1507, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1508, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1509, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1510, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1511, NULL, NULL, 'Websense Allowed: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1512, NULL, NULL, 'Websense Allowed: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1513, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1514, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1516, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1517, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1518, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1519, NULL, NULL, 'Websense Allowed: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1520, NULL, NULL, 'Websense Allowed: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1521, NULL, NULL, 'Websense Allowed: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1523, NULL, NULL, 'Websense Allowed: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1524, NULL, NULL, 'Websense Allowed: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1525, NULL, NULL, 'Websense Allowed: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1526, NULL, NULL, 'Websense Allowed: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1527, NULL, NULL, 'Websense Allowed: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1528, NULL, NULL, 'Websense Allowed: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1529, NULL, NULL, 'Websense Allowed: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1530, NULL, NULL, 'Websense Allowed: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1531, NULL, NULL, 'Websense Allowed: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1801, NULL, NULL, 'Websense Allowed: Non-HTTP', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1900, NULL, NULL, 'Websense Allowed: Custom-Category 1', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1901, NULL, NULL, 'Websense Allowed: Custom-Category 2', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1902, NULL, NULL, 'Websense Allowed: Custom-Category 3', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1903, NULL, NULL, 'Websense Allowed: Custom-Category 4', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1904, NULL, NULL, 'Websense Allowed: Custom-Category 5', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1905, NULL, NULL, 'Websense Allowed: Custom-Category 6', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1906, NULL, NULL, 'Websense Allowed: Custom-Category 7', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1907, NULL, NULL, 'Websense Allowed: Custom-Category 8', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1908, NULL, NULL, 'Websense Allowed: Custom-Category 9', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 1909, NULL, NULL, 'Websense Allowed: Custom-Category 10', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10001, NULL, NULL, 'Websense Blocked: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10002, NULL, NULL, 'Websense Blocked: Business and Economy', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10003, NULL, NULL, 'Websense Blocked: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10004, NULL, NULL, 'Websense Blocked: Government', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10005, NULL, NULL, 'Websense Blocked: News and Media', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10006, NULL, NULL, 'Websense Blocked: Religion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10007, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10008, NULL, NULL, 'Websense Blocked: Special Events', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10009, NULL, NULL, 'Websense Blocked: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10010, NULL, NULL, 'Websense Blocked: Abortion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10011, NULL, NULL, 'Websense Blocked: Advocacy Groups', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10012, NULL, NULL, 'Websense Blocked: Entertainment', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10013, NULL, NULL, 'Websense Blocked: Gambling', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10014, NULL, NULL, 'Websense Blocked: Games', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10015, NULL, NULL, 'Websense Blocked: Illegal or Questionable', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10016, NULL, NULL, 'Websense Blocked: Job Search', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10017, NULL, NULL, 'Websense Blocked: Shopping', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10018, NULL, NULL, 'Websense Blocked: Sports', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10019, NULL, NULL, 'Websense Blocked: Tasteless', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10020, NULL, NULL, 'Websense Blocked: Travel', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10021, NULL, NULL, 'Websense Blocked: Vehicles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10022, NULL, NULL, 'Websense Blocked: Violence', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10023, NULL, NULL, 'Websense Blocked: Weapons', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10024, NULL, NULL, 'Websense Blocked: Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10025, NULL, NULL, 'Websense Blocked: Militancy and Extremist', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10026, NULL, NULL, 'Websense Blocked: Racism and Hate', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10027, NULL, NULL, 'Websense Blocked: Health', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10028, NULL, NULL, 'Websense Blocked: Information technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10029, NULL, NULL, 'Websense Blocked: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10064, NULL, NULL, 'Websense Blocked: User-Defined', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10065, NULL, NULL, 'Websense Blocked: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10066, NULL, NULL, 'Websense Blocked: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10067, NULL, NULL, 'Websense Blocked: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10068, NULL, NULL, 'Websense Blocked: Business and Economy', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10069, NULL, NULL, 'Websense Blocked: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10070, NULL, NULL, 'Websense Blocked: Entertainment', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10072, NULL, NULL, 'Websense Blocked: Government', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10073, NULL, NULL, 'Websense Blocked: Government', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10074, NULL, NULL, 'Websense Blocked: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10075, NULL, NULL, 'Websense Blocked: Information Technology - Proxy Avoidance', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10076, NULL, NULL, 'Websense Blocked: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10078, NULL, NULL, 'Websense Blocked: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10079, NULL, NULL, 'Websense Blocked: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10080, NULL, NULL, 'Websense Blocked: Information Technology - Hacking', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10081, NULL, NULL, 'Websense Blocked: News and Media', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10082, NULL, NULL, 'Websense Blocked: Religion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10083, NULL, NULL, 'Websense Blocked: Religion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10084, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10085, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10086, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10087, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10088, NULL, NULL, 'Websense Blocked: Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10089, NULL, NULL, 'Websense Blocked: Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10090, NULL, NULL, 'Websense Blocked: Drugs - Abused Drugs', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10091, NULL, NULL, 'Websense Blocked: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10092, NULL, NULL, 'Websense Blocked: Abortion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10093, NULL, NULL, 'Websense Blocked: Abortion', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10094, NULL, NULL, 'Websense Blocked: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10095, NULL, NULL, 'Websense Blocked: Adult Material', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10096, NULL, NULL, 'Websense Blocked: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10097, NULL, NULL, 'Websense Blocked: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10098, NULL, NULL, 'Websense Blocked: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10099, NULL, NULL, 'Websense Blocked: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10100, NULL, NULL, 'Websense Blocked: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10101, NULL, NULL, 'Websense Blocked: Shopping', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10102, NULL, NULL, 'Websense Blocked: Shopping', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10103, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10107, NULL, NULL, 'Websense Blocked: Sport', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10108, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10109, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10110, NULL, NULL, 'Websense Blocked: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10111, NULL, NULL, 'Websense Blocked: Drugs - Marijuana', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10112, NULL, NULL, 'Websense Blocked: Productivity', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10113, NULL, NULL, 'Websense Blocked: Bandwidth - Personal Network Storage and Backup', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10114, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10115, NULL, NULL, 'Websense Blocked: Bandwidth - Peer-to-Peer File Sharing', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10116, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10117, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10118, NULL, NULL, 'Websense Blocked: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10121, NULL, NULL, 'Websense Blocked: Education', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10122, NULL, NULL, 'Websense Blocked: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10123, NULL, NULL, 'Websense Blocked: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10124, NULL, NULL, 'Websense Blocked: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10125, NULL, NULL, 'Websense Blocked: Social Organizations', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10126, NULL, NULL, 'Websense Blocked: Security', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10128, NULL, NULL, 'Websense Blocked: Security - Malicious Web Sites', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10138, NULL, NULL, 'Websense Blocked: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10146, NULL, NULL, 'Websense Blocked: Miscellaneous', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10147, NULL, NULL, 'Websense Blocked: Miscellaneous - Images (Media)', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10148, NULL, NULL, 'Websense Blocked: Miscellaneous - Image Servers', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10149, NULL, NULL, 'Websense Blocked: Miscellaneous - Private IP Addresses', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10150, NULL, NULL, 'Websense Blocked: Miscellaneous - Content Delivery Networks', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10151, NULL, NULL, 'Websense Blocked: Miscellaneous - Dynamic Content', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10152, NULL, NULL, 'Websense Blocked: Miscellaneous - Network Errors', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10153, NULL, NULL, 'Websense Blocked: Miscellaneous - Uncategorized', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10154, NULL, NULL, 'Websense Blocked: Security - Spyware', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10156, NULL, NULL, 'Websense Blocked: Miscellaneous', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10164, NULL, NULL, 'Websense Blocked: Security - Phishing and Other Frauds', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10166, NULL, NULL, 'Websense Blocked: Security - Keyloggers', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10167, NULL, NULL, 'Websense Blocked: Security - Potentially Unwanted Software', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10172, NULL, NULL, 'Websense Blocked: Security - Bot Networks', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10191, NULL, NULL, 'Websense Blocked: Extended Protection', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10192, NULL, NULL, 'Websense Blocked: Extended Protection - Elevated Exposure', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10193, NULL, NULL, 'Websense Blocked: Extended Protection - Emerging Exploits', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10194, NULL, NULL, 'Websense Blocked: Extended Protection - Potentially Damaging Content', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10195, NULL, NULL, 'Websense Blocked: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10196, NULL, NULL, 'Websense Blocked: Internet Communication', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10200, NULL, NULL, 'Websense Blocked: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10201, NULL, NULL, 'Websense Blocked: Information Technology', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10202, NULL, NULL, 'Websense Blocked: Parked Domain', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10203, NULL, NULL, 'Websense Blocked: Business and Economy', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10204, NULL, NULL, 'Websense Blocked: Society and Lifestyles', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10205, NULL, NULL, 'Websense Blocked: Security - Malicious Embedded Link', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10206, NULL, NULL, 'Websense Blocked: Security - Malicious Embedded iFrame', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10207, NULL, NULL, 'Websense Blocked: Security - Suspicious Embedded Link', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10208, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10209, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10210, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10211, NULL, NULL, 'Websense Blocked: Bandwidth', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10212, NULL, NULL, 'Websense Blocked: Extended Protection', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10213, NULL, NULL, 'Websense Blocked: Security - Potentially Exploited Documents', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10214, NULL, NULL, 'Websense Blocked: Security - Mobile Malware', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10215, NULL, NULL, 'Websense Blocked: Information Technology - Unauthorized Mobile Marketplaces', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10216, NULL, NULL, 'Websense Blocked: Security - Custom-Encrypted Uploads', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10217, NULL, NULL, 'Websense Blocked: Security - Files Containing Passwords', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10218, NULL, NULL, 'Websense Blocked: Security - Advanced Malware Command and Control', 1, 5);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 10219, NULL, NULL, 'Websense Blocked: Security - Advanced Malware Payloads', 1, 5);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11500, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11501, NULL, NULL, 'Websense Blocked: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11502, NULL, NULL, 'Websense Blocked: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11503, NULL, NULL, 'Websense Blocked: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11504, NULL, NULL, 'Websense Blocked: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11505, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11506, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11507, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11508, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11509, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11510, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11511, NULL, NULL, 'Websense Blocked: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11512, NULL, NULL, 'Websense Blocked: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11513, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11514, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11516, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11517, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11518, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11519, NULL, NULL, 'Websense Blocked: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11520, NULL, NULL, 'Websense Blocked: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11521, NULL, NULL, 'Websense Blocked: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11523, NULL, NULL, 'Websense Blocked: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11524, NULL, NULL, 'Websense Blocked: Social Web - Facebook', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11525, NULL, NULL, 'Websense Blocked: Social Web - YouTube', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11526, NULL, NULL, 'Websense Blocked: Social Web - Twitter', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11527, NULL, NULL, 'Websense Blocked: Social Web - LinkedIn', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11528, NULL, NULL, 'Websense Blocked: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11529, NULL, NULL, 'Websense Blocked: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11530, NULL, NULL, 'Websense Blocked: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11531, NULL, NULL, 'Websense Blocked: Social Web - Various', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11801, NULL, NULL, 'Websense Blocked: Non-HTTP', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11900, NULL, NULL, 'Websense Blocked: Custom-Category 1', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11901, NULL, NULL, 'Websense Blocked: Custom-Category 2', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11902, NULL, NULL, 'Websense Blocked: Custom-Category 3', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11903, NULL, NULL, 'Websense Blocked: Custom-Category 4', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11904, NULL, NULL, 'Websense Blocked: Custom-Category 5', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11905, NULL, NULL, 'Websense Blocked: Custom-Category 6', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11906, NULL, NULL, 'Websense Blocked: Custom-Category 7', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11907, NULL, NULL, 'Websense Blocked: Custom-Category 8', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11908, NULL, NULL, 'Websense Blocked: Custom-Category 9', 0, 0);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (19004, 11909, NULL, NULL, 'Websense Blocked: Custom-Category 10', 0, 0);