DELETE FROM plugin WHERE id = '9300';
DELETE FROM plugin_sid where plugin_id = '9300';
DELETE FROM software_cpe where plugin = 'sonicwall_sonicos:9300';
INSERT IGNORE INTO software_cpe (cpe, name, version, line, vendor, plugin) VALUES ('cpe:/o:SonicWall:SonicOS:5.9.1.0-22o','SonicWall','SonicOS','','Dell','sonicwall_sonicos:9300');
INSERT IGNORE INTO plugin (id, type, name, description, product_type, vendor) VALUES ('9300',1,'sonicwall_sonicos','SonicWall','10','Dell');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 1154, 3, 1, 'SonicWall: Application Control Detection Alert');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 1155, 3, 1, 'SonicWall: Application Control Prevention Alert');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 1226, 3, 1, 'SonicWall: HTTPS Handshake');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 1232, 3, 1, 'SonicWall: NTP Request sent');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 1233, 3, 1, 'SonicWall: Unhandled link-local or multicast IPv6 packet dropped');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 265, 3, 1, 'SonicWall: User logged out - inactivity timer expired');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 34, 3, 1, 'SonicWall: Login screen timed out');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 537, 3, 1, 'SonicWall: Connection Closed');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 608, 3, 1, 'SonicWall: IPS Detection Alert:');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 82, 3, 1, 'SonicWall: Possible port scan detected');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 97, 3, 1, 'SonicWall: Web site hit');
INSERT INTO `plugin_sid` (`plugin_id`,`sid`,`reliability`, `priority`, `name`) VALUES (9300, 98, 3, 1, 'SonicWall: Connection Opened');